version: '3.8'
services:
  postgres:
    image: "postgres"
    container_name: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=password
    
  backend:
    build: .
    container_name: backend_app
    ports:
      - 3333:3333
    environment:
      POSTGRES_URL : postgresql://postgres:password@postgres:5432
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgresdb_data:
  